resources:
  pipelines:
    employee_cdc_pipeline:
      name: cdc-automated-workflow-${bundle.target}
      catalog: ${var.catalog}
      target: ${var.schema}
      channel: CURRENT
      edition: ADVANCED
      serverless: true
      continuous: false
      configuration:
        pipeline.reprocess_days: ${var.reprocess_days}
        pipeline.environment: ${var.environment}
        pipeline.catalog: ${var.catalog}
        pipeline.schema: ${var.schema}
      libraries:
        - file:
            path: ../src/transformations/pipeline_config.py
        - file:
            path: ../src/transformations/schemas.py
        - file:
            path: ../src/transformations/schemas_silver.py
        - file:
            path: ../src/transformations/read_and_write_to_raw.py
        - file:
            path: ../src/transformations/read_and_write_to_silver_schema_enforced.py
        - file:
            path: ../src/transformations/read_and_write_to_silver_curated_dlt_dq.py
        - file:
            path: ../src/transformations/read_and_write_to_silver_curated_alternate_dq.py
        - file:
            path: ../src/transformations/write_to_gold_table.py
        - file:
            path: ../src/transformations/write_to_gold_table_cdc.py
