resources:
  pipelines:
    employee_cdc_pipeline:
      name: cdc-workflow-${bundle.target}
      catalog: ${var.catalog}
      target: ${var.schema}
      channel: CURRENT
      edition: ADVANCED
      serverless: true
      continuous: false
      configuration:
        pipeline.reprocess_days: ${var.reprocess_days}
        pipeline.environment: ${var.environment}
        pipeline.catalog: ${var.catalog}
        pipeline.schema: ${var.schema}
      root_path: ../src/transformations
      libraries:
        - glob:
            include: ../src/transformations/**
